name: CI Modular API

on:
  push:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Levantar API local con Uvicorn
      run: |
        pip install uvicorn
        uvicorn main:app --host 0.0.0.0 --port 8080 &
        sleep 5

    - name: Ejecutar test del endpoint
      run: |
        pip install requests
        python tests/test_endpoint.py

    - name: Build Docker image
      run: docker build -t api-cancer .

    - name: Login to DockerHub
      if: success()
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image
      if: success()
      run: docker tag api-cancer ${{ secrets.DOCKER_USERNAME }}/api-cancer:latest && docker push ${{ secrets.DOCKER_USERNAME }}/api-cancer:latest
