name: CI Modular API

on:
  push:
    branches: [main]  # Ejecutar solo en la rama principal

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies for test script
      run: pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t api-cancer .

    - name: Run container in background
      run: docker run -d -p 5000:5000 --name api-cancer api-cancer

    - name: Wait for API to be ready
      run: |
        echo "Esperando que la API esté disponible..."
        for i in {1..10}; do
          curl --silent http://localhost:5000/health && break
          sleep 3
        done

    - name: Ejecutar test del endpoint
      run: python tests/test_endpoint.py

    - name: Stop and remove container
      run: docker stop api-cancer && docker rm api-cancer

    - name: Login to DockerHub
      if: success()
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image to DockerHub
      if: success()
      run: |
        docker tag api-cancer ${{ secrets.DOCKER_USERNAME }}/api-cancer:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/api-cancer:latest
